name: chronos_stable
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - joblib
  - holidays
  - jsonschema
  - tensorboard

  - pip:
      - torch==2.7.1
      - torchvision
      - torchaudio
      - --index-url https://download.pytorch.org/whl/cu128
